repos:
  - repo: local
    hooks:
      - id: poetry-check-toml
        name: poetry-check-toml
        entry: poetry
        language: system
        files: ^pyproject\.toml$
        pass_filenames: false
        args: [ "check" ]

      - id: black
        name: black
        entry: poetry
        language: system
        types: [ python ]
        args: [ "run", "black" ]

      - id: isort
        name: isort
        entry: poetry
        language: system
        types: [ python ]
        args: [ "run", "isort" ]

      - id: flake8
        name: flake8
        entry: poetry
        language: system
        types: [ python ]
        args: [ "run", "flake8" ]

      - id: pydocstyle
        name: pydocstyle
        entry: poetry
        language: system
        types: [ python ]
        args: [ "run", "pydocstyle" ]

      - id: mypy
        name: mypy
        entry: poetry
        language: system
        types: [ python ]
        args: [ "run", "mypy" ]

      - id: pytest
        name: pytest
        entry: poetry
        language: system
        always_run: true
        pass_filenames: false
        args: [ "run", "pytest" ]
